server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /ragApplications

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #MySQL???
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ragapplication?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    initial-size: 8
    max-active: 16
    min-idle: 8
    max-wait: 60000
    test-while-idle: true
    test-on-borrow: true
    test-on-return: fals


mybatis:
  #指定pojo扫描包位置让mybatis自动扫描到指定义的pojo包下
  type-aliases-package: com.example.ragapplication.pojo
  #指定位置扫描Mapper接口对应的XML文件 classpath:xml文件位置
  mapper-locations: classpath:com/example/ragapplication/mapper/*.xml
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true


